---

########################################################################
# Generate operational-tasks Jenkins jobs.
########################################################################

- name: Create a list of operational tasks
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/operational-tasks/
  when: item.state == 'file'
  register: operational_tasks_jobs

- name: Trim skipped operational tasks
  set_fact:
    operational_tasks_jobs_trimmed: "{{ operational_tasks_jobs | trim_skipped() }}"

- name: "Generate jobs for operational-tasks directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_jobs_trimmed.results }}"

- name: "Generate jobs for operational-tasks configuration profile config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_jobs_trimmed.results }}"

- name: "Generate jobs for operational-tasks config.xml for basic jobs"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_basic_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Author/Publish component parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-authorpublish-component.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_authorpublish_component_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Dispatcher component parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-dispatcher-component.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_dispatcher_component_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Profile parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-aem-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_aem_profile_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with deploy package parameters"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-deploy-package.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_deploy_package_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with disable saml parameters"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-disable-saml.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_disable_saml_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with enable saml parameters"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-enable-saml.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_enable_saml_params }}"

# - name: "Generate jobs for operational-tasks config.xml for jobs with export package parameters"
#   template:
#     src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-export-package.xml.j2'
#     dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
#     mode: '0644'
#   with_nested:
#     - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
#     - "{{ operational_tasks_with_export_package_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with import package parameters"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-import-package.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_import_package_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with deployment descriptor parameter"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1] is match('.*-consolidated') else 'full-set' }}"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-deployment-descriptor.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_deployment_descriptor_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with export descriptor parameter"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1] is match('.*-consolidated') else 'full-set' }}"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-export-descriptor.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_export_descriptor_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Test Suite basic parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-test.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_aem_test_suite_basic_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Test Suite AEM architecture parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-test-architecture-type.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_aem_test_suite_aem_architecture_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Test Suite AEM architecture parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-test-recovery.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_aem_test_suite_recovery_params }}"

- name: "Generate jobs for operational-tasks config.xml for jobs with AEM Test Suite AEM architecture parameter"
  template:
    src: '../../../templates/ansible/jenkins/config/jobs-operational-tasks-test-aem-security.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/operational-tasks/{{ item[0].item.path }}/{{ item[1] }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ operational_tasks_with_aem_test_suite_security_params }}"
