---
aws:
  library:
    s3_bucket: overwrite-me
    s3_path: library

aem_opencloud:
  version: 4.0.0-pre.2
  config:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  custom_manager_steps:
    artifact_url:
  custom_image_provisioner:
    artifact_url:
  custom_stack_provisioner:
    artifact_url:
  descriptors:
    consolidated:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
    full-set:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
  jenkins_sharedlibs:
    repo_url: https://github.com/shinesolutions/aem-opencloud-manager
    repo_branch: jenkins-sharedlibs-4.0.0-pre.2

jenkins:
  protocol: http
  host: overwrite-me
  port: 8080
  username: overwrite-me
  password: overwrite-me
  agent:
    docker_image: 'shinesolutions/aem-platform-buildenv:latest'
    docker_args: ''
