aws:
  region: overwrite-me
  library:
    s3_bucket: overwrite-me
    s3_path: library
  dns_records:
    author_dispatcher:
      author_dispatcher_hosted_zone_name: overwrite-me
    publish_dispatcher:
      publish_dispatcher_hosted_zone_name: overwrite-me
    author_publish_dispatcher:
      author_publish_dispatcher_hosted_zone_name: overwrite-me
aem_opencloud:
  version: 5.17.2-pre.0
  enable_slack_notifications: false
  skip_gen_config_download: false
  config:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  custom_manager_steps:
    artifact_url: null
  custom_image_provisioner:
    artifact_url: null
  custom_stack_provisioner:
    artifact_url: null
  descriptors:
    consolidated:
      deployment_descriptor_url: null
      export_descriptor_url: null
      content_healthcheck_descriptor_url: null
    full-set:
      deployment_descriptor_url: null
      export_descriptor_url: null
      content_healthcheck_descriptor_url: null
  jenkins_sharedlibs:
    repo_url: https://github.com/shinesolutions/aem-opencloud-manager
    repo_branch: main
    repo_branch_prefix: ''''''
jenkins:
  protocol: http
  host: overwrite-me
  port: 8080
  username: overwrite-me
  password: overwrite-me
  agent:
    label: ''
    docker_image: shinesolutions/aem-platform-buildenv:3.2.0
    docker_args: ''
  os:
    jenkins_home: null
    user: null
    group: null
