---
aws:
  region: overwrite-me
  library:
    s3_bucket: overwrite-me
    s3_path: library
  vpc_id: overwrite-me
  dns_records:
    author_dispatcher:
      author_dispatcher_hosted_zone_name: overwrite-me
    publish_dispatcher:
      publish_dispatcher_hosted_zone_name: overwrite-me
    author_publish_dispatcher:
      author_publish_dispatcher_hosted_zone_name: overwrite-me

aem_opencloud:
  version: 4.1.0-pre.7
  enable_slack_notifications: false
  config:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  custom_manager_steps:
    artifact_url:
  custom_image_provisioner:
    artifact_url:
  custom_stack_provisioner:
    artifact_url:
  descriptors:
    consolidated:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
    full-set:
      deployment_descriptor_url:
      export_descriptor_url:
      content_healthcheck_descriptor_url:
  jenkins_sharedlibs:
    repo_url: https://github.com/hoomaan-kh/aem-opencloud-manager
    repo_branch: switch-dns

jenkins:
  protocol: http
  host: overwrite-me
  port: 8080
  username: overwrite-me
  password: overwrite-me
  agent:
    docker_image: 'shinesolutions/aem-platform-buildenv:1.1.0'
    docker_args: ''
  os:
    jenkins_home:
    user:
    group:
