---
aws:
  library:
    s3_bucket: overwrite-me
    s3_path: library

aem_opencloud:
  version: 3.8-pre.0
  library:
    packer_aem: 3.7.0
    aem_aws_stack_builder: 3.6.0
    aem_stack_manager_messenger: 2.2.0
    aem_test_suite: 0.9.10
  config:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  custom_manager_steps:
    artifact_url: https://overwrite-me/overwrite-me.tar.gz
  jenkins_sharedlibs:
    repo_url: overwrite-me
    repo_branch: master

jenkins:
  protocol: http
  host: localhost
  port: 8080
  username: overwrite-me
  password: overwrite-me
